export const DAILY_TIPS = [
  "Drinking plenty of water and staying hydrated can help reduce bloating and cramps during your period.",
  "Gentle exercise like walking or yoga can help improve blood flow and reduce period pain.",
  "Applying a heating pad or hot water bottle to your lower abdomen can help relax muscles and ease cramps.",
  "Eating magnesium-rich foods like dark chocolate, spinach, and bananas can help reduce PMS symptoms.",
  "Getting enough sleep is crucial for hormonal balance and managing mood swings during your cycle.",
  "Reducing caffeine and salt intake a few days before your period can help minimize bloating and breast tenderness.",
  "Tracking your cycle regularly helps you predict your next period and understand your body's patterns.",
  "Ginger tea has natural anti-inflammatory properties that can help soothe menstrual cramps.",
  "Iron-rich foods like lentils, beans, and lean meats are important to replenish iron lost during your period.",
  "Practicing deep breathing or meditation can help manage stress and emotional changes throughout your cycle.",
  "Wearing comfortable, breathable cotton underwear can help prevent irritation and maintain hygiene.",
  "Omega-3 fatty acids found in walnuts and flaxseeds can help reduce the severity of period pain.",
  "Taking a warm bath can help relax your body and mind, providing relief from menstrual discomfort.",
  "Listen to your body—if you feel tired, it's okay to rest and take it easy during your period.",
  "Chamomile tea can help reduce muscle spasms and promote a sense of calm during your cycle.",
  "Avoid heavy, greasy foods if you experience digestive issues or nausea during your period.",
  "Vitamin B6 found in chickpeas and salmon can help regulate mood and reduce irritability.",
  "Maintaining a balanced diet with plenty of fruits and vegetables supports overall hormonal health.",
  "If your period pain is severe and interferes with daily life, consider consulting a healthcare professional.",
  "Simple stretching can help relieve lower back pain often associated with menstruation.",
  "Stay positive! Your cycle is a natural part of your body's health and vitality.",
  "Using a menstrual cup or reusable pads is an eco-friendly and cost-effective alternative to disposables.",
  "Keep a small 'period kit' in your bag with extra pads, wipes, and a change of underwear for peace of mind.",
  "Calcium-rich foods like yogurt and almonds can help reduce the severity of PMS symptoms.",
  "Acupressure on specific points on your legs and feet may help alleviate menstrual discomfort.",
  "Limit sugary snacks to avoid energy crashes and mood dips during your period.",
  "Try to maintain a consistent sleep schedule to help regulate your body's internal clock.",
  "Journaling your feelings can be a great way to process emotional changes during your cycle.",
  "Light massage with essential oils like lavender can help soothe tension and promote relaxation.",
  "Remember that every person's cycle is unique—what works for others might be different for you.",
  "Stay informed! Learning about your reproductive health empowers you to make the best choices for your body."
];
